site_name: Machine Learning Foundations

theme:
    name: material
    logo: assets/images/logo.png
    features:
        #- navigation.tabs
        - header.autohide
        - navigation.indexes
nav:
  - Home: index.md
  - Week-1:
    - week-1/outline.md
    - week-1/linear_algebra.md
    - week-1/ml_problem.md
    - week-1/dataset.md
  - Week-2:
    - week-2/Calculus.md
  - Week-3:
    - week-3/outline.md
    - week-3/linear_model.md
    - week-3/system_1.md
    - week-3/system_2.md
    - week-3/least_squares.md
    - week-3/best_fit.md
    - week-3/projections.md
  - Week-4:
    - week-4/outline.md
    - week-4/transformations.md
    - week-4/eigenvectors.md
    - week-4/char_polynomial.md
    - week-4/computation.md
    - week-4/diagonalization.md
    - week-4/tests_diagonal.md
  - Appendix:
    - appendix/gradients.md
    - appendix/cauchy_schwarz.md
    - appendix/rank_one.md
    - appendix/matrix_product.md
    - appendix/density_estimation.md 
  - Contribute: contribute.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      css_style:
        width: "100%"

